name: school_management
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.0
  dropdown_search: ^6.0.1  # Update ke versi yang mendukung null safety
  date_time_picker: ^2.0.0  # Update ke versi terbaru
  fzregex: ^2.0.0
  flutter_svg: ^2.0.10+1  # Update ke versi terbaru
  flare_flutter: ^3.0.0  # Update ke versi terbaru
  http: ^1.2.2  # Ganti ke versi terbaru yang mendukung null safety
  fluttertoast: ^8.0.9  # Ganti ke versi yang tersedia
  image_picker: ^1.1.2  # Update ke versi terbaru
  select_form_field: ^2.2.0
  url_launcher: ^6.0.20  # Update ke versi terbaru
  photo_view: ^0.15.0
  webview_flutter: ^4.10.0
  pdf: ^3.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/notification.png
    - assets/
